#!/bin/sh
# Kill K9 v1.0
# Created by |SaMaN|
# $Id: killk9,v 1.1.1.1 2002/09/09 12:26:24 tom Exp $
DIR=`pwd`
DATE=`date +"%a, %b %e %Y"`
TIME=`date +"%H:%M:%S %Z"`
IRCDPID="k9.pid"

if [ ! -r $IRCDPID ]; then
clear
echo "|--------------------------------------------|"
echo "|              **** ERROR ****               "
echo "|             Possible problems:             "
echo "| (1) $IRCDPID not found                     "
echo "| (2) K9 IRC Services is not running         "
echo "|--------------------------------------------|"
else
PID=`cat $IRCDPID`
kill -9 $PID >/dev/null 2>&1
rm -f $IRCDPID
echo "|----------------------------------------|"
echo "| K9 IRC Services successfully shutdown.  "    
echo "| Directory: $DIR                         "
echo "| Date: $DATE                             "
echo "| Time: $TIME                             "
echo "| Process ID: $PID                        "
echo "|----------------------------------------|"
fi
